version: "3.8"
services:
  backend:
    image: ${DOCKER_USERNAME}/backend:latest
    container_name: app_backend
    expose:
      - "5000"   # only available to other containers, not host
    environment:
      - NODE_ENV=production

  frontend:
    image: your-docker-username/frontend:latest
    container_name: frontend
    ports:
    - "80:80"
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  nginx:
    image: nginx:alpine
    container_name: app_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"  # exposed to host
    depends_on:
      - frontend
      - backend
