version: "3.8"
services:
  backend:
    image: ${DOCKER_USERNAME}/backend:latest
    container_name: app_backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
  frontend:
    image: ${DOCKER_USERNAME}/frontend:latest
    container_name: app_frontend
    ports:
      - "80:80"
