version: "3.8"

services:
  frontend:
    image: ${DOCKER_USERNAME}/frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: ${DOCKER_USERNAME}/backend:latest
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
