FROM node:18

WORKDIR /app

# Install extra languages (python, g++, java)
RUN apt-get update && apt-get install -y \
    python3 python3-pip \
    g++ \
    openjdk-17-jdk \
    && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 5000
CMD ["node", "index.js"]
